### ISSUE TITLE
Private Messaging Feature

### ISSUE THREAD

**Issue by maddy2101** [NeoBlack/T3Bot#9]
Purpose: Botty deliveres messages from one user to another, when the recipient is online.

Proposal:
`/msg @botty tell @olly about forge:12345`
`/msg @botty tell @olly about review:12345`

that makes the bot post a private message to the recipient, telling him his attention is required for the given forge- or gerrit address. If the user is currently away, the message will be delivered when the user comes back online.

**Comment by NeoBlack** [comment]
the new feature is now in testing phase. before merge into master and roll out on LIVE, the new feature must be documented in the wiki.
